name: coda
#description:

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=2.18.6 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  logger:
  uuid:
  mqtt_client: ^9.7.3 # 7.1.0
  provider: ^6.0.5
  flutter_bloc: ^8.1.1
  go_router: ^6.0.0
  percent_indicator: ^4.2.2
  font_awesome_flutter: ^10.3.0
  webview_flutter: ^4.0.2
  equatable: ^2.0.5
  path_provider: ^2.0.11
  fab_circular_menu: ^1.0.2
  flutter_typeahead: 4.1.1
  bloc: ^8.1.0
  cupertino_icons: ^1.0.2
  draggable_scrollbar: ^0.1.0
  flutter_riverpod: ^2.1.3
  flutter_slidable: ^2.0.0
  collection: ^1.16.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true
